http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80; # Exit port (ipv4)
        listen [::]:80; # Exit port (ipv6)

        client_max_body_size 300M; # Maximum file size

        location / {
            # This would be the directory where your React app's static files are stored at
            root /usr/share/nginx/html;
            try_files $uri /index.html;
        }
    }
}

events {
    worker_connections 1024;
}
